### ISSUE TITLE
Test PassingValueIntoConstructor_SetsValueProperty fails on non-English locale system

### ISSUE THREAD

**Issue by krypt-lynx** [martindevans/Cassowary.net#4]
variable.ToString() outputs "[name:111,1]" (comma instead of period) on my system
Looks like this (not checked others yet) using system default locale instead of `CultureInfo.InvariantCulture`

**Comment by martindevans** [comment]
That's a good point, I expect this same bug is duplicated in a few places. Would you be interested in submitting a PR just to add in the `CultureInfo.InvariantCulture` in the appropriate places?

**Comment by krypt-lynx** [comment]
I will do. Out of curiosity, what are you using this lib for?

**Comment by martindevans** [comment]
> I will do.

Thanks ❤️ 

> what are you using this lib for?

I'm not using it any more. Back when I developed it I was using it to procedurally generate 2D layouts of things e.g. facades for procedurally generated buildings (see the video at the bottom of [this post](https://martindevans.me/heist-game/2015/05/29/Procedural-Generation-Of-Facades-And-Other-Miscellania/) if you're interested).

**Comment by krypt-lynx** [comment]
#5 
For whatever reason github does not allows to link existing issue in request

**Comment by krypt-lynx** [comment]
It is not what I expected, to be honest.
I need a crossplatform constraints implementation to try to insert it into Unity game. And crossplatform support using native libs is a rabbit hole I don't want to dive into

**Comment by martindevans** [comment]
I've merged that PR, thanks very much :D
